### ISSUE TITLE
Fix OCR problems

### ISSUE THREAD

**Issue by psychelzh** [psychelzh/phdrule#1]
There are still many OCR problems. Use screenshots to add them here.

**Comment by psychelzh** [comment]
![](https://i.imgur.com/3sZMRlR.jpg)

**Comment by kingzevin** [comment]
OCR: "作为一个博士生，你必须接受这样的事实——你所在的位置并非是学术等级的最顶端，而一个刚**人学**的博士生只不过是初出茅庐的新手。"

**Comment by psychelzh** [comment]
@kingzevin Thanks. I will try to fix them these days.
